// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
	"time"
)

type Achievement struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsUnique    bool           `json:"is_unique"`
	BundleID    sql.NullInt64  `json:"bundle_id"`
	OwnerID     string         `json:"owner_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type AchievementBundle struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	OwnerID     string         `json:"owner_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type EarnedAchievement struct {
	ID            int64     `json:"id"`
	UserID        string    `json:"user_id"`
	AchievementID int64     `json:"achievement_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Integration struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type IntegrationPermission struct {
	ID                  int64         `json:"id"`
	IntegrationID       int64         `json:"integration_id"`
	AchievementBundleID sql.NullInt64 `json:"achievement_bundle_id"`
	AchievementID       sql.NullInt64 `json:"achievement_id"`
	CreatedAt           time.Time     `json:"created_at"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	AvatarUrl string `json:"avatar_url"`
}
